name: Build Electron Package

on:
  workflow_dispatch:
    inputs:
      build-windows:
        description: 'Do you want to build for Windows?'
        required: false
        default: 'yes'
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install root dependencies
        run: npm install 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies for client (frontend)
        run: |
          cd client
          npm install --legacy-peer-deps
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies for server (backend)
        run: |
          cd server
          npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build App for Windows
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Zip Windows package (from dist folder)
        run: |
          Compress-Archive -Path ./dist/* -DestinationPath "windows-hub-b2c.zip"
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Windows ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-hub-b2c.zip
          path: windows-hub-b2c.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install root dependencies
        run: npm install  
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies for client (frontend)
        run: |
          cd client
          npm install --legacy-peer-deps
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies for server (backend)
        run: |
          cd server
          npm install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install required packages for Linux build
        run: sudo apt-get update && sudo apt-get install -y fakeroot rpm 
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build App for Ubuntu
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Zip Ubuntu package (from dist folder)
        run: |
          zip -r "ubuntu-hub-b2c.zip" dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Ubuntu ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-hub-b2c.zip
          path: ubuntu-hub-b2c.zip

  upload-release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Windows ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-hub-b2c.zip

      - name: Download Ubuntu ZIP artifact
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-hub-b2c.zip

      - name: Create or Update GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: 'Release notes for version ${{ github.run_number }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Windows package to GitHub Releases
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          --data-binary @"windows-hub-b2c.zip" \
          -H "Content-Type: application/zip" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=windows-hub-b2c.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Ubuntu package to GitHub Releases
        run: |
          curl -L -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          --data-binary @"ubuntu-hub-b2c.zip" \
          -H "Content-Type: application/zip" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=ubuntu-hub-b2c.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
