name: Build Electron Package

on:
  workflow_dispatch: # Permite disparar o build manualmente
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(echo $VERSION | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo "New version: $NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version
          echo "version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push new version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${{ env.version }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      # Instalar dependências na raiz
      - name: Install root dependencies
        run: |
          npm install 

      # Instalar dependências do frontend (client)
      - name: Install dependencies for client (frontend)
        run: |
          cd client
          npm install --legacy-peer-deps

      # Instalar dependências do backend (server)
      - name: Install dependencies for server (backend)
        run: |
          cd server
          npm install

      - name: Build App for Windows
        run: npm run build

      - name: Zip Windows package
        run: zip -r windows-$(node -p "require('./package.json').version").zip dist/

      - name: Upload Windows package to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: windows-$(node -p "require('./package.json').version").zip
          asset_name: windows-$(node -p "require('./package.json').version").zip
          asset_content_type: application/zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Adiciona o GH_TOKEN aqui

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      # Instalar dependências na raiz
      - name: Install root dependencies
        run: |
          npm install  

      # Instalar dependências do frontend (client)
      - name: Install dependencies for client (frontend)
        run: |
          cd client
          npm install --legacy-peer-deps

      # Instalar dependências do backend (server)
      - name: Install dependencies for server (backend)
        run: |
          cd server
          npm install

      - name: Install required packages for Linux build
        run: sudo apt-get update && sudo apt-get install -y fakeroot rpm 

      - name: Build App for Ubuntu
        run: npm run build

      - name: Zip Ubuntu package
        run: zip -r ubuntu-$(node -p "require('./package.json').version").zip dist/

      - name: Upload Ubuntu package to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ubuntu-$(node -p "require('./package.json').version").zip
          asset_name: ubuntu-$(node -p "require('./package.json').version").zip
          asset_content_type: application/zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Adiciona o GH_TOKEN aqui
