name: Build Electron Package

on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          NEW_VERSION=$(npm version patch --no-git-tag-version) # Incrementa a versão (patch level)
          echo "::set-output name=version::${NEW_VERSION}"

      - name: Commit new version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${{ steps.extract-version.outputs.version }}"
          git push

  build-windows:
    runs-on: windows-latest
    needs: update-version

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install dependencies
        run: npm install

      - name: Build App for Ubuntu
        run: npm run build

      - name: Build Electron App for Ubuntu
        run: npm run package

      - name: Zip the Windows build
        run: |
          VERSION=${{ needs.update-version.outputs.version }}
          powershell Compress-Archive -Path dist/* -DestinationPath dist/windows-${VERSION}.zip

      - name: Upload Windows package to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/windows-${{ needs.update-version.outputs.version }}.zip
          asset_name: windows-${{ needs.update-version.outputs.version }}.zip
          asset_content_type: application/zip

  build-ubuntu:
    runs-on: ubuntu-latest
    needs: update-version

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.10.0'

      - name: Install dependencies
        run: npm install

      - name: Install required packages for Linux build
        run: sudo apt-get update && sudo apt-get install -y fakeroot rpm 

      - name: Build App for Ubuntu
        run: npm run build

      - name: Build Electron App for Ubuntu
        run: npm run package

      - name: Zip the Linux build
        run: |
          VERSION=${{ needs.update-version.outputs.version }}
          zip -r dist/ubuntu-${VERSION}.zip dist/*

      - name: Upload Linux package to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/ubuntu-${{ needs.update-version.outputs.version }}.zip
          asset_name: ubuntu-${{ needs.update-version.outputs.version }}.zip
          asset_content_type: application/zip
